version: "3.7"

services:
  solution:
    build: 
      context: ./solution
    ports: 
      - 5000:5000
    

  checker:
    build: checker
    image: mike0sv/sf_docker_check
    container_name: checker
    depends_on: 
      - solution
  